# Generated by Django 4.2.7 on 2023-12-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('department', models.TextField()),
            ],
        ),
    ]
